### ISSUE TITLE
Error should be friendly when user enter wrong DID

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#139]
Should not dump error message like this

```
$ forge create-chain 
✖ The chain name should not be empty
? Please input chain name: chain-1
? Please input block time (in seconds): 5
? Do you want to customize token config for this chain? No
? Do you want to enable "feel lucky" (poke) feature for this chain? No
? Please input token holder address (run `forge wallet:create` to generate if do not have one) () abcAbtDid.toTypeInfo.decodeError Error: Cannot convert DID string to byte array: Unsupported encoding
    at toBytes (/usr/local/lib/node_modules/@arcblock/forge-cli/node_modules/@arcblock/did/lib/util.js:21:11)
    at toTypeInfo (/usr/local/lib/node_modules/@arcblock/forge-cli/node_modules/@arcblock/did/lib/index.js:158:19)
    at isValid (/usr/local/lib/node_modules/@arcblock/forge-cli/node_modules/@arcblock/did/lib/index.js:204:20)
    at Object.validate (/usr/local/lib/node_modules/@arcblock/forge-cli/src/cli/node/config/lib.js:304:16)
    at /usr/local/lib/node_modules/@arcblock/forge-cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/@arcblock/forge-cli/node_modules/run-async/index.js:24:19
    at filter.then.isValid (/usr/local/lib/node_modules/@arcblock/forge-cli/node_modules/inquirer/lib/prompts/base.js:93:13)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

**Comment by wangshijun** [comment]
`@arcblock/did` `isValid`
