### ISSUE TITLE
Bug: can't start latest workshop

### ISSUE THREAD

**Issue by polunzh** [ArcBlock/forge-cli#296]
```
$ SHELL=/bin/zsh HOME=/Users/zhenqiang WORKSHOP_CONFIG=/Users/zhenqiang/.forge_chains/forge_solar/forge_release.toml ERL_AFLAGS="-sname forge-workshop-e2cf1817f9bb7713307949ada414cb68" FORGE_CONFIG=/Users/zhenqiang/.forge_chains/forge_solar/forge_release.toml /Users/zhenqiang/.forge_cli/release/forge_workshop
/0.39.1/bin/forge_workshop start
2019-10-18 09:56:25.660421 Multiple -~p given to erl, using the first, ~p
        sname
        "forge-workshop-e2cf1817f9bb7713307949ada414cb68"
=WARNING REPORT==== 18-Oct-2019::09:56:25.660421 ===
Multiple -sname given to erl, using the first, "forge-workshop-e2cf1817f9bb7713307949ada414cb68"
[info] Application forge_workshop exited: exited in: ForgeWorkshop.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: nil
            (forge_workshop) lib/forge_workshop/application.ex:103: ForgeWorkshop.Application.apply_config/0
            (forge_workshop) lib/forge_workshop/application.ex:9: ForgeWorkshop.Application.start/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
{"Kernel pid terminated",application_controller,"{application_start_failure,forge_workshop,{bad_return,{{'Elixir.ForgeWorkshop.Application',start,[normal,[]]},{'EXIT',{{case_clause,nil},[{'Elixir.ForgeWorkshop.Application',apply_config,0,[{file,\"lib/forge_workshop/application.ex\"},{line,103}]},{'Elixir.ForgeWorkshop.Application',start,2,[{file,\"lib/forge_workshop/application.ex\"},{line,9}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,277}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,forge_workshop,{bad_return,{{'Elixir.ForgeWorkshop.Application',start,[normal,[]]},{'EXIT',{{case_clause,nil},[{'Elixir.Forge

Crash dump is being written to: erl_crash.dump...done
```

Tested v0.38.4, 0.38.9, 0.39.1, can't start.

**Comment by polunzh** [comment]
https://github.com/ArcBlock/forge-workshop/issues/69

**Comment by polunzh** [comment]
latest workshop requires schema in config
